name: Deploy to cloudtype
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: quddnddl35/oregano
          stage: main
          yaml: >
            name: oregano

            app: java@17

            options:
              ports: 8080
              env:
                - name: fetchJob
                  value: https://apis.data.go.kr/B552583/job/job_list_env?serviceKey=sFd76vlvMGfsJNeEHd0ifb8V08Jb0kPQHvDAg6rlqp1W%2BFstDVJ0E7o5oAS9INRW7qA9rB4PY0XNiDV%2BJD5OSQ%3D%3D&pageNo=1&numOfRows=400
                - name: numberOfRegisteredDisabledPeople
                  value: https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=ZDIxNzk0ZjBkYzU4MjkxYjlkOTBlMGMyOTdkMmQ2MGI=&itmId=00+&objL1=ALL&objL2=CHUT0+&objL3=TT+&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Y&newEstPrdCnt=1&prdInterval=2023&orgId=117&tblId=DT_11761_N005
                - name: estimatedSixMonthsIncomes
                  value: https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=ZDIxNzk0ZjBkYzU4MjkxYjlkOTBlMGMyOTdkMmQ2MGI=&itmId=num+wage+&objL1=ALL&objL2=&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=H&newEstPrdCnt=2&orgId=383&tblId=DT_38304_2013_N014
                - name: REACT_APP_BASE_URL
                  value: https://web-oregano-react-lxfol2lf38345220.sel5.cloudtype.app
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
